export const FETCH_KETTLES_START = 'FETCH_KETTLES_START';
export const FETCH_KETTLES_SUCCESS = 'FETCH_KETTLES_SUCCESS';
export const FETCH_KETTLES_FAILURE = 'FETCH_KETTLES_FAILURE';

export const FETCH_KETTLE_BY_ID_START = 'FETCH_KETTLE_BY_ID_START';
export const FETCH_KETTLE_BY_ID_SUCCESS = 'FETCH_KETTLE_BY_ID_SUCCESS';
export const FETCH_KETTLE_BY_ID_FAILURE = 'FETCH_KETTLE_BY_ID_FAILURE';

export const ADD_KETTLE_TO_CART = 'ADD_KETTLE_TO_CART';
export const DELETE_KETTLE_FROM_CART = 'DELETE_KETTLE_FROM_CART';
export const CHANGE_KETTLE_COUNT_IN_CART = 'CHANGE_KETTLE_COUNT_IN_CART';
export const CLEAR_CART = 'CLEAR_CART'; 

export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';

export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';

export const UPDATE_CUSTOMER_DATA = 'UPDATE_CUSTOMER_DATA';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'; 